sudo: false
language: python
services:
  - memcached
  - postgresql
  - redis-server
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
install:
  - make develop
before_script:
  - psql -c 'create database sentry;' -U postgres
script:
  - flake8
  - py.test
